name: Update Nginx Version

on:
  schedule:
    # Run every day at 2:00 AM UTC
    - cron: '0 2 * * *'
  workflow_dispatch:  # Allows manual triggering

jobs:
  update-nginx:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Update Nginx image to latest
        run: |
          # Get the latest nginx version from Docker Hub
          latest_version=$(curl -s https://registry.hub.docker.com/v1/repositories/nginx/tags | jq -r '.[].name' | grep -E '^[0-9]+\.[0-9]+$' | sort -V | tail -1)
          echo "Latest nginx version: $latest_version"
          
          # Update the deployment.yaml with the new version
          sed -i "s|image: nginx:.*|image: nginx:$latest_version|" my-app/deployment.yaml

      - name: Commit and push changes
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add my-app/deployment.yaml
          git commit -m "Update nginx to version $latest_version"
          git push