name: Update Nginx Version

on:
  schedule:
    # Run every day at 2:00 AM UTC
    - cron: '0 2 * * *'
  workflow_dispatch:  # Allows manual triggering

jobs:
  update-nginx:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.PAT }}  # Use the PAT for authentication

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Update Nginx image to latest
        run: |
          # Install jq if not available
          sudo apt-get update && sudo apt-get install -y jq
          
          # Get the latest nginx version from Docker Hub
          latest_version=$(curl -s https://registry.hub.docker.com/v2/nginx/tags/list | jq -r '.tags[]' | grep -E '^[0-9]+\.[0-9]+$' | sort -V | tail -1)
          echo "Latest nginx version: $latest_version"
          echo "NGINX_VERSION=$latest_version" >> $GITHUB_ENV
          
          # Update the deployment.yaml with the new version
          sed -i "s|image: nginx:.*|image: nginx:$latest_version|" my-app/deployment.yaml
          
          # Show the updated file
          cat my-app/deployment.yaml

      - name: Commit and push changes
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add my-app/deployment.yaml
          git commit -m "Update nginx to version ${{ env.NGINX_VERSION }}"
          git push origin main